import React from 'react';
import {Box, Typography} from '@mui/material';
import Message, {MessageProps} from './Message';

const ConversationHistory: React.FC = () => {
    const messages: MessageProps[] = [
        {sender: 'user', text: '1Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},
        {sender: 'assistant', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},
        {sender: 'user', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},
        {sender: 'assistant', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},
        {sender: 'user', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},
        {sender: 'assistant', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},
        {sender: 'user', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},
        {sender: 'assistant', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},
        {sender: 'user', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},
        {sender: 'assistant', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis dolor leo, id fermentum turpis congue quis. Nulla fermentum orci ligula, in euismod turpis porttitor in. Curabitur eget pharetra lacus. Ut id tellus a tellus tincidunt vulputate et vel lectus. Nulla vulputate leo erat, id feugiat lorem vestibulum sed. Morbi vehicula ipsum ac libero congue condimentum. Etiam vitae imperdiet tortor. Phasellus iaculis ante quis felis lobortis, non ultricies diam porttitor. Sed aliquam, augue ac efficitur porta, leo odio gravida ante, a bibendum risus quam eu lectus. Donec dignissim diam vitae lectus sagittis volutpat.\n' +
                '\n' +
                'Donec efficitur in est non sagittis. Sed vitae velit viverra, semper orci id, iaculis lacus. Nullam eu lorem nunc. Phasellus non purus id neque facilisis vehicula in non lorem. Vivamus hendrerit lacinia diam, eget fringilla nunc vestibulum maximus. Aliquam ut ipsum maximus, consequat nunc nec, malesuada quam. Integer porttitor tortor a cursus lacinia. Sed est neque, pulvinar id finibus vel, malesuada nec sapien. Sed magna lacus, auctor ut facilisis et, rutrum in diam. Aenean lacinia odio molestie egestas suscipit.\n' +
                '\n' +
                'Pellentesque non commodo sapien, vel dignissim nisi. Donec condimentum quam nec tempus mollis. Mauris in efficitur sapien. Aliquam interdum ac felis eget pellentesque. Nullam mollis, sapien non imperdiet pretium, eros tortor sollicitudin tortor, at laoreet mauris quam sit amet felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent vel semper diam. Suspendisse in pharetra sem. Vivamus eros elit, iaculis sit amet leo ac, suscipit eleifend erat.\n' +
                '\n' +
                'Nullam accumsan vitae urna malesuada consequat. Sed consectetur fermentum sapien a rutrum. Donec ut erat quis nulla ullamcorper cursus id quis metus. Etiam feugiat commodo massa ac eleifend. Suspendisse tincidunt leo sit amet sapien tincidunt, dictum faucibus tortor aliquam. Mauris nibh sapien, fermentum vitae dolor ut, accumsan iaculis tortor. Sed nec erat massa. Aenean lacus mi, varius at porta nec, congue ac nunc. Maecenas dapibus erat in velit mollis, a elementum lorem sodales. Mauris nec ex non nisi commodo euismod vitae a turpis. Integer non velit diam. Sed vehicula libero odio, pharetra posuere nisl placerat eu. Sed placerat tortor ac eros luctus feugiat.\n' +
                '\n' +
                'Suspendisse porta lorem quis tempor auctor. Quisque at dapibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas suscipit risus elit, ut aliquet metus viverra at. Maecenas commodo, mi ac volutpat dictum, mi orci bibendum enim, nec suscipit ex lacus non lorem. Proin accumsan lectus in nulla semper tempor. Quisque sit amet dolor suscipit, consequat dolor sit amet, volutpat magna. Donec gravida sapien sapien. Pellentesque vulputate elementum viverra.'},

    ];

    return (
        <Box
            display="flex"
            flexDirection="column"
            height="100%"
            width="100%"
            overflow="auto"
        >
            <Typography variant="h6" m={1}>
                Conversation History
            </Typography>
            <Box flexGrow={1}>
                {messages.map((message, index) => (
                    <Message key={index} sender={message.sender} text={message.text}/>
                ))}
            </Box>
        </Box>
    );
};

export default ConversationHistory;
